// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2526_2221050613_BaiThi.Data;

#nullable disable

namespace _2526_2221050613_BaiThi.Migrations
{
    [DbContext(typeof(DoanDb))]
    [Migration("20260620092207_PhuongXa")]
    partial class PhuongXa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("_2526_2221050613_BaiThi.Models.TinhThanh", b =>
                {
                    b.Property<string>("MaTinh")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenTinh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaTinh");

                    b.ToTable("TinhThanhs");
                });
#pragma warning restore 612, 618
        }
    }
}
